### ISSUE TITLE
DEMO MODE: report/logging functionality in tagging UI

### ISSUE THREAD

**Issue by rtbs-dev** [usnistgov/nestor-tmp2#13]
For research purposes: should have a mode that autosaves progress when annotating the standard excavator dataset

**Comment by emhastings** [comment]
We've been talking about how often/when the autosaves should happen (every x seconds/by percent completion/etc.), and I was thinking that maybe we could combine them and have a timer going, but save by percent completion (maybe every 5-10%?). That way we would have timestamps to know how long it takes people, but it would resolve the problem of how often to save when a lot of progress happening at the very beginning and slower thereafter.  If we did this, we would still want to have the pause button for making sure the timer is accurate if they take breaks.

Other thoughts for this mode (not sure if they belong here or in separate issues):

- We should probably call it "Research Mode" rather than "Demo" as that seems more accurate, and then there could be an actual "Demo" mode for presentations, etc. in the future.

- If possible, we could have the app skip the initial dialogue boxes and just load right into the tagging using "standard" settings, in order to streamline and make sure all participants would be using the same settings (although we may need to ask them for an identifier to use in the autosave filenames)

- We should make in clear in the app somewhere (or at least the docs) where these autosaved files will live, because users who aren't familiar with the tool or are less computer-savvy may have trouble finding these to share with the researchers.

**Comment by msngit** [comment]
So, one suggestion that I had about the 'autosave' is that, instead of being time/percentage based, could it be activity based. That is, can things like event callbacks be used, that indicate how many clicks the user has made. This becomes a measure of the amount of interaction (s)he has made with the tool. The autosave could be a function of the number of events then.

**Comment by rtbs-dev** [comment]
@msngit I do like the idea that user interaction is important. However, I don't know if it's a good anchor for recording progress, since the variablility we are trying to measure is largely associated with variation in user workflow. Anchoring to that variablility will normalize it away, to some degree. 

I had talked with @saschaMoccozet about this at length and we both really like the idea of measuring the time-stamp (plus maybe number of actions now, too), but *anchoring* on percentage completed. Mainly because that's ultimately the goal we are presenting users with, which all users have in common.

**Comment by rtbs-dev** [comment]
I believe this can be closed, any further issues with this mode can be addressed in new, less general issues.
