### ISSUE TITLE
doesn't work in IE

### ISSUE THREAD

**Issue by timothysprock** [usnistgov/nestor-tmp2#43]
diagrams in visual dashboard don't load in internet explorer. IE compatibility is essential.

**Comment by rtbs-dev** [comment]
Thanks for the report. I'll leave a note on our project board. However, until we have actual web developers working on this, the target demographic for the dashboard functionality is not one of the 5% or so that use it (industry or not). 

e.g. [here](https://www.sitepoint.com/browsers-website-support/), or [here](https://www.xfive.co/blog/stop-supporting-ie10-ie9-ie8/). 

IE has to die sooner or later xD
