### ISSUE TITLE
Issue when importing text columns 

### ISSUE THREAD

**Issue by ghost** [usnistgov/nestor-tmp2#55]
I'm working with a dataset that has quite a large number of Text Columns that contain relevant information that I would like to tag. It is such that I have about 111 columns that I would like to import. I overlooked setting a category for one of the checked items (on the Text Columns? window) and it threw an unhandled error message. After this occurred, I was unable to proceed to the next window even when I filled in the description or changed the boxes that I selected.

After restarting the program, and making sure that I filled in all of the category descriptions, I was successful on proceeding to the next window. I'm not sure if the category of each column header must be filled in or it was due to the large number of columns I was trying to import. This is not blocking me from progress but did require a reset of the program, so I figured I would report it.

**Comment by rtbs-dev** [comment]
@etbelski This is possibly due to utf-8 handling errors in version 0.2x. The unhandled error would have crashed the Qt session, which is why you got locked out. 

After restarting, I'm imagining that the utf errors were mitigated by processing through Pandas the first time, but I'm unsure without digging in a bit more. There shouldn't have been issues with selecting any or none of the categories -- they aren't required for annotation (and in fact are not presented to the user upon loading a dataset starting in v0.3, instead existing as a optional annotation through the menu).

**Comment by ghost** [comment]
@tbsexton since I'm using v0.3 now, I'll close this and reopen if experience it again.
